### Wide format is where we have a single row for every data point with multiple columns to hold the values of various attributes (In simple words more columns less rows)

### Long format is where for each data point we have as many rows as the number of attributes and each row contains the value of a particular  attribute for a given data points.(In simple words more rows and less columns)

### melt : This is use to convert Wide data into long data
### pivot : This is use to convert Long data into Wide data

In [23]:
# import 
import numpy as np
import pandas as pd
import seaborn as sns

In [5]:
# melt 
pd.DataFrame({'cse' : [120]})
pd.DataFrame({'cse':[120]}).melt()

  variable  value
0      cse    120

In [6]:
# melt another example:
pd.DataFrame({'cse':[120],'ece':[100],'mech':[150]}).melt(var_name='branch',value_name='num_students')

  branch  num_students
0    cse           120
1    ece           100
2   mech           150

In [14]:
# melt example
pd.DataFrame({
    'branch':['cse','cse_ai','cse_gen_ai','ece'],
    '2023':[100,210,130,213],
    '2024':[190,329,340,489],
    '2025':[290,870,652,832],
    '2026':[500,600,800,900]
} 
).melt(id_vars=['branch'],var_name='year',value_name='students') # id_vars = columns you want to keep unchanged (as identifiers) mean it just skip the column  or to change

        branch  year  students
0          cse  2023       100
1       cse_ai  2023       210
2   cse_gen_ai  2023       130
3          ece  2023       213
4          cse  2024       190
5       cse_ai  2024       329
6   cse_gen_ai  2024       340
7          ece  2024       489
8          cse  2025       290
9       cse_ai  2025       870
10  cse_gen_ai  2025       652
11         ece  2025       832
12         cse  2026       500
13      cse_ai  2026       600
14  cse_gen_ai  2026       800
15         ece  2026       900

In [22]:
# Real world example of melt :
death=pd.read_csv('time_series_covid19_deaths_global.csv')
confirm=pd.read_csv('time_series_covid19_confirmed_global.csv')
death.head() # Data is in wide format
confirm.head() # Data is in wide format
death=death.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_deaths')
Confirm=confirm.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_cases')
#merge
Confirm.merge(death,on=['Province/State','Country/Region','Lat','Long','date'])[['Country/Region','date','num_cases','num_deaths']]

              Country/Region     date  num_cases  num_deaths
0                Afghanistan  1/22/20          0           0
1                    Albania  1/22/20          0           0
2                    Algeria  1/22/20          0           0
3                    Andorra  1/22/20          0           0
4                     Angola  1/22/20          0           0
...                      ...      ...        ...         ...
311248    West Bank and Gaza   1/2/23     703228        5708
311249  Winter Olympics 2022   1/2/23        535           0
311250                 Yemen   1/2/23      11945        2159
311251                Zambia   1/2/23     334661        4024
311252              Zimbabwe   1/2/23     259981        5637

[311253 rows x 4 columns]

### Pivot table : The pivot table takes simple column wise data input and groups the entries into a two-Dimensional table that provides a multidimensional summarized of the data

In [24]:
df=sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [25]:
df.groupby('sex')[['total_bill']].mean()

        total_bill
sex
Male     20.744076
Female   18.056897