### Wide format is where we have a single row for every data point with multiple columns to hold the values of various attributes (In simple words more columns less rows)

### Long format is where for each data point we have as many rows as the number of attributes and each row contains the value of a particular  attribute for a given data points.(In simple words more rows and less columns)

### melt : This is use to convert Wide data into long data
### pivot : This is use to convert Long data into Wide data

In [23]:
# import 
import numpy as np
import pandas as pd
import seaborn as sns

In [5]:
# melt 
pd.DataFrame({'cse' : [120]})
pd.DataFrame({'cse':[120]}).melt()

  variable  value
0      cse    120

In [6]:
# melt another example:
pd.DataFrame({'cse':[120],'ece':[100],'mech':[150]}).melt(var_name='branch',value_name='num_students')

  branch  num_students
0    cse           120
1    ece           100
2   mech           150

In [14]:
# melt example
pd.DataFrame({
    'branch':['cse','cse_ai','cse_gen_ai','ece'],
    '2023':[100,210,130,213],
    '2024':[190,329,340,489],
    '2025':[290,870,652,832],
    '2026':[500,600,800,900]
} 
).melt(id_vars=['branch'],var_name='year',value_name='students') # id_vars = columns you want to keep unchanged (as identifiers) mean it just skip the column  or to change

        branch  year  students
0          cse  2023       100
1       cse_ai  2023       210
2   cse_gen_ai  2023       130
3          ece  2023       213
4          cse  2024       190
5       cse_ai  2024       329
6   cse_gen_ai  2024       340
7          ece  2024       489
8          cse  2025       290
9       cse_ai  2025       870
10  cse_gen_ai  2025       652
11         ece  2025       832
12         cse  2026       500
13      cse_ai  2026       600
14  cse_gen_ai  2026       800
15         ece  2026       900

In [22]:
# Real world example of melt :
death=pd.read_csv('time_series_covid19_deaths_global.csv')
confirm=pd.read_csv('time_series_covid19_confirmed_global.csv')
death.head() # Data is in wide format
confirm.head() # Data is in wide format
death=death.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_deaths')
Confirm=confirm.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_cases')
#merge
Confirm.merge(death,on=['Province/State','Country/Region','Lat','Long','date'])[['Country/Region','date','num_cases','num_deaths']]

              Country/Region     date  num_cases  num_deaths
0                Afghanistan  1/22/20          0           0
1                    Albania  1/22/20          0           0
2                    Algeria  1/22/20          0           0
3                    Andorra  1/22/20          0           0
4                     Angola  1/22/20          0           0
...                      ...      ...        ...         ...
311248    West Bank and Gaza   1/2/23     703228        5708
311249  Winter Olympics 2022   1/2/23        535           0
311250                 Yemen   1/2/23      11945        2159
311251                Zambia   1/2/23     334661        4024
311252              Zimbabwe   1/2/23     259981        5637

[311253 rows x 4 columns]

### Pivot table : The pivot table takes simple column wise data input and groups the entries into a two-Dimensional table that provides a multidimensional summarized of the data

In [24]:
df=sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.groupby('sex')[['total_bill']].mean()

        total_bill
sex
Male     20.744076
Female   18.056897

In [30]:
# using groupby
df.groupby(['sex','smoker'])['total_bill'].mean().unstack()

smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [32]:
#  using Pivot table
df.pivot_table(index='sex',columns='smoker',values='total_bill')

smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [36]:
#aggfunc : using this you can easily use maths function on dataset It will apply on all the values u want to display
df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='sum')

smoker      Yes       No
sex
Male    1337.07  1919.75
Female   593.27   977.68

In [42]:
# Multidimensional
df.pivot_table(index=['sex','smoker'],columns=['day','time'],values='total_bill')

day                 Thur               Fri                Sat        Sun
time               Lunch Dinner      Lunch  Dinner     Dinner     Dinner
sex    smoker
Male   Yes     19.171000    NaN  11.386667  25.892  21.837778  26.141333
       No      18.486500    NaN        NaN  17.475  19.929063  20.403256
Female Yes     19.218571    NaN  13.260000  12.200  20.266667  16.540000
       No      15.899167  18.78  15.980000  22.750  19.003846  20.824286

In [44]:
# also using aggfunc
df.pivot_table(index=['sex','smoker'],columns=['day','time'],aggfunc={'size':'mean','tip':'max','total_bill':'sum'})

                   size                                               tip  \
day                Thur              Fri              Sat       Sun  Thur
time              Lunch Dinner     Lunch Dinner    Dinner    Dinner Lunch
sex    smoker
Male   Yes     2.300000    NaN  1.666667    2.4  2.629630  2.600000  5.00
       No      2.500000    NaN       NaN    2.0  2.656250  2.883721  6.70
Female Yes     2.428571    NaN  2.000000    2.0  2.200000  2.500000  5.00
       No      2.500000    2.0  3.000000    2.0  2.307692  3.071429  5.17

                                                total_bill                \
day                    Fri           Sat    Sun       Thur           Fri
time          Dinner Lunch Dinner Dinner Dinner      Lunch Dinner  Lunch
sex    smoker
Male   Yes       NaN  2.20   4.73  10.00    6.5     191.71    NaN  34.16
       No        NaN   NaN   3.50   9.00    6.0     369.73    NaN    NaN
Female Yes       NaN  3.48   4.30   6.50    4.0     134.53    NaN  39.78
       No        3.0  3.00   3.25   4.67    5.2     381.58  18.78  15.98


day                       Sat     Sun
time           Dinner  Dinner  Dinner
sex    smoker
Male   Yes     129.46  589.62  392.12
       No       34.95  637.73  877.34
Female Yes      48.80  304.00   66.16
       No       22.75  247.05  291.54

In [45]:
#margins 
df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='sum',margins=True)

smoker      Yes       No      All
sex
Male    1337.07  1919.75  3256.82
Female   593.27   977.68  1570.95
All     1930.34  2897.43  4827.77

In [46]:
# plotting graph
df=pd.read_csv('expense_data.csv')
df.head()

,Date,Account,Category,Subcategory,Note,INR,Income/Expense,Note.1,Amount,Currency,Account.1
0,3/2/2022 10:11,CUB - online payment,Food,NaN,Brownie,50.0,Expense,NaN,50.0,INR,50.0
1,3/2/2022 10:11,CUB - online payment,Other,NaN,To lended people,300.0,Expense,NaN,300.0,INR,300.0
2,3/1/2022 19:50,CUB - online payment,Food,NaN,Dinner,78.0,Expense,NaN,78.0,INR,78.0
3,3/1/2022 18:56,CUB - online payment,Transportation,NaN,Metro,30.0,Expense,NaN,30.0,INR,30.0
4,3/1/2022 18:22,CUB - online payment,Food,NaN,Snacks,67.0,Expense,NaN,67.0,INR,67.0

In [48]:
df['Date'] = pd.to_datetime(df['Date'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            277 non-null    datetime64[us]
 1   Account         277 non-null    str
 2   Category        277 non-null    str
 3   Subcategory     0 non-null      float64
 4   Note            273 non-null    str
 5   INR             277 non-null    float64
 6   Income/Expense  277 non-null    str
 7   Note.1          0 non-null      float64
 8   Amount          277 non-null    float64
 9   Currency        277 non-null    str
 10  Account.1       277 non-null    float64
dtypes: datetime64[us](1), float64(5), str(5)
memory usage: 23.9 KB