### Wide format is where we have a single row for every data point with multiple columns to hold the values of various attributes (In simple words more columns less rows)

### Long format is where for each data point we have as many rows as the number of attributes and each row contains the value of a particular  attribute for a given data points.(In simple words more rows and less columns)

### melt : This is use to convert Wide data into long data
### pivot : This is use to convert Long data into Wide data

In [2]:
# import 
import numpy as np
import pandas as pd

In [5]:
# melt 
pd.DataFrame({'cse' : [120]})
pd.DataFrame({'cse':[120]}).melt()

  variable  value
0      cse    120

In [6]:
# melt another example:
pd.DataFrame({'cse':[120],'ece':[100],'mech':[150]}).melt(var_name='branch',value_name='num_students')

  branch  num_students
0    cse           120
1    ece           100
2   mech           150

In [8]:
# melt example
pd.DataFrame({
    'branch':['cse','cse_ai','cse_gen_ai','ece'],
    '2023':[100,210,130,213],
    '2024':[190,329,340,489],
    '2025':[290,870,652,832],
    '2026':[500,600,800,900]
} 
).melt(id_vars=['branch'],var_name='year',value_name='students') # id_vars = columns you want to keep unchanged (as identifiers)

        branch  year  students
0          cse  2023       100
1       cse_ai  2023       210
2   cse_gen_ai  2023       130
3          ece  2023       213
4          cse  2024       190
5       cse_ai  2024       329
6   cse_gen_ai  2024       340
7          ece  2024       489
8          cse  2025       290
9       cse_ai  2025       870
10  cse_gen_ai  2025       652
11         ece  2025       832
12         cse  2026       500
13      cse_ai  2026       600
14  cse_gen_ai  2026       800
15         ece  2026       900

In [ ]:
# Real world example of melt :
death=pd.read_csv('')